languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
enableEmoji = true

theme = 'dd-cv'
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

title = 'David_Delarosa-CV'


[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#75509f"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#75509f"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#75509f"

pages = 2

# Set this param to 'true' to swap the bar positions
swapColumns = false
